## Numpy Arrays

In [1]:
#normal python list
mylst = [1, 2, 3]

In [2]:
import numpy as np

In [3]:
np.array(mylst)

array([1, 2, 3])

In [4]:
#2d array
mymat = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(mymat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
##array create
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(5)

array([0.65184618, 0.67422142, 0.15348152, 0.30486553, 0.19745927])

In [15]:
np.random.randn(5)

array([-0.08516462,  0.10014972,  0.37288814,  0.68084407, -2.1844782 ])

In [17]:
#random integer
np.random.randint(1, 100, 10)

array([58, 23, 40, 30,  7, 97, 70, 61, 89,  8])

In [23]:
arr = np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
nparr = np.random.randint(0,50, 10)

In [26]:
nparr

array([16, 16, 32, 22, 36, 39, 11, 21, 35, 36])

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
nparr.max()

39

In [30]:
nparr.min()

11

In [31]:
nparr.argmax()

5

In [32]:
nparr.argmin()

6

In [33]:
nparr.dtype

dtype('int32')