In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [5]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [6]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [7]:
arr[5:]==100

array([False, False, False, False, False, False])

In [8]:
arr[5:]=100

In [9]:
arr

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100, 100])

In [10]:
arr = np.arange(0, 11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

If we make variable of sliced array, it will changed the main array also but not if we make a copy of array

In [15]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr_2d[0][0]

1

In [18]:
arr_2d[0,0]

1

In [19]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [20]:
arrr = np.arange(1, 11)

In [21]:
arrr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
bool_arr = arrr > 5

In [23]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [24]:
arrr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [25]:
arrr_2d = np.arange(50).reshape(5,10)

In [26]:
arrr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arrr_2d[3:5,2:4]